name: extract untranslated # Workflow to extract untranslated strings with LocaleOps

on:
  repository_dispatch:
    types: [localeops_extract] # Triggered via repository_dispatch event from LocaleOps

jobs:
  extract:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Run LocaleOps to extract untranslated strings for configured locales
      - name: extract
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass GitHub token to LocaleOps as TOKEN
          # DEBUG: "true"
        run: |
          output=$(npx @localeops/localeops extract)
          echo "$output"