# =============================================================================
# LocaleOps Apply Translations Workflow
# =============================================================================
#
# This workflow applies completed translations to your repository.
# It's designed for asynchronous translation workflows where translations
# are completed by external services, human translators, or APIs.
#
# Workflow:
# 1. Triggered via repository_dispatch event
# 2. Receives translations in the event payload
# 3. Applies translations using LocaleOps
# 4. Creates a pull request with the changes
#
# Trigger this workflow using GitHub API:
# ```bash
# curl -X POST \
#   -H "Authorization: token YOUR_GITHUB_TOKEN" \
#   -H "Accept: application/vnd.github.v3+json" \
#   https://api.github.com/repos/OWNER/REPO/dispatches \
#   -d '{"event_type":"localeops_apply","client_payload":{"translations":{...}}}'
# ```
#
# Requirements:
# - GITHUB_TOKEN: Automatically provided by GitHub Actions
#
# =============================================================================

name: apply translations

on:
  repository_dispatch:
    types: [localeops_apply]  # Triggered via repository_dispatch event

# Prevent multiple apply workflows from running simultaneously
concurrency:
  group: localeops_apply
  cancel-in-progress: false

jobs:
  apply_translations:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # Required to push commits
      pull-requests: write   # Required to create pull requests

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Configure git for commits created by LocaleOps
      - name: configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Extract translations from repository_dispatch payload
      # The payload should contain: {translations: {locale: [{filePath, resourcePath, value}]}}
      - name: set env vars
        run: |
          {
            echo "TRANSLATIONS<<EOF"
            echo '${{ toJson(github.event.client_payload.translations) }}'
            echo "EOF"
          } >> "$GITHUB_ENV"

      # Apply translations to locale files and create PR
      - name: run localeops
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for creating PR
        run: npx @localeops/localeops apply "${TRANSLATIONS}"
